volumes:
  storage:
services:
  backend:
    restart: on-failure
    build:
      context: ..
      dockerfile: deploy/file-service.Dockerfile
      # target: build
    volumes:
      - storage:/storage
    ports:
      - "50051:50051"
      - "40001:40000"
    environment:
      - DEBUG=0
      - GRPC_ADDRESS=:50051
      - STORAGE_DIR=/storage
  frontend:
    restart: on-failure
    build:
      context: ..
      dockerfile: deploy/client.Dockerfile
      target: build
    depends_on:
      - backend
    ports:
      - "8081:8080"
      - "40002:40000"
    environment:
      - GRPC_SERVER_ADDRESS=backend:50051
      - HTTP_ADDRESS=:8080
      - DEBUG=1
